import type { DiagramStyle } from '../types';

export const blueprint: DiagramStyle = {
  id: 'blueprint',
  displayName: 'Blueprint',
  dark: true,
  canvas: {
    background: '#0a1929',
    gridColor: '#1e3a5f',
    gridStyle: 'lines',
  },
  nodeDefaults: {
    fill: 'transparent',
    stroke: '#4fc3f7',
    strokeWidth: 1.5,
    borderRadius: 2,
    shadow: '0 0 8px rgba(79, 195, 247, 0.15)',
    fontFamily: "'JetBrains Mono', 'Fira Code', 'Consolas', monospace",
    fontSize: 13,
    fontColor: '#e0f7fa',
    fontWeight: 400,
  },
  iconDefaults: {
    color: '#4fc3f7',
  },
  edgeDefaults: {
    stroke: '#4fc3f7',
    strokeWidth: 1,
    type: 'straight',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: ['#4fc3f7', '#00e5ff', '#0288d1', '#00838f', '#26c6da', '#80deea', '#0277bd'],
  shapeColors: {
    rectangle: 'transparent',
    roundedRectangle: 'transparent',
    diamond: '#0284c7',
    circle: '#22d3ee',
    parallelogram: '#38bdf8',
    hexagon: '#0ea5e9',
    document: '#38bdf8',
    cloud: '#0288d1',
    stickyNote: '#164e63',
    textbox: 'transparent',
    blockArrow: '#4fc3f7',
    chevronArrow: '#00e5ff',
    doubleArrow: '#0288d1',
    circularArrow: '#26c6da',
    ellipse: '#22d3ee',
    group: 'rgba(79, 195, 247, 0.08)',
  },
  defaultPaletteId: 'cyber',
};
