import type { DiagramStyle } from '../types';

export const colorfulGradient: DiagramStyle = {
  id: 'colorfulGradient',
  displayName: 'Colorful Gradient',
  canvas: {
    background: '#fafbfc',
    gridColor: '#e8ecf0',
    gridStyle: 'dots',
  },
  nodeDefaults: {
    fill: '#6366f1',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 12,
    shadow: '0 2px 8px rgba(0, 0, 0, 0.08)',
    fontFamily: "'Inter', 'Segoe UI', sans-serif",
    fontSize: 14,
    fontColor: '#ffffff',
    fontWeight: 600,
  },
  edgeDefaults: {
    stroke: '#9ca3af',
    strokeWidth: 1,
    type: 'smoothstep',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: [
    '#ef4444',
    '#f59e0b',
    '#10b981',
    '#3b82f6',
    '#8b5cf6',
    '#ec4899',
    '#06b6d4',
    '#f97316',
  ],
  shapeColors: {
    rectangle: '#6366f1',
    roundedRectangle: '#6366f1',
    diamond: '#f59e0b',
    circle: '#10b981',
    parallelogram: '#ec4899',
    hexagon: '#ef4444',
    document: '#06b6d4',
    cloud: '#8b5cf6',
    stickyNote: '#fbbf24',
    textbox: 'transparent',
    blockArrow: '#f97316',
    chevronArrow: '#3b82f6',
    doubleArrow: '#ec4899',
    circularArrow: '#ef4444',
  },
};
