import type { DiagramStyle } from '../types';

export const cyberC2: DiagramStyle = {
  id: 'cyberC2',
  displayName: 'Slate Command',
  dark: false,
  canvas: {
    background: '#f0f4f8',
    gridColor: '#d0d8e0',
    gridStyle: 'lines',
  },
  nodeDefaults: {
    fill: '#FFFFF0',
    stroke: '#000000',
    strokeWidth: 1.5,
    borderRadius: 6,
    shadow: '0 1px 3px rgba(0,0,0,0.15)',
    fontFamily: "'Arial', 'Helvetica Neue', Helvetica, sans-serif",
    fontSize: 12,
    fontColor: '#000000',
    fontWeight: 400,
  },
  iconDefaults: {
    color: '#000000',
  },
  edgeDefaults: {
    stroke: '#000000',
    strokeWidth: 1.5,
    type: 'smoothstep',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: ['#8BA5BF', '#A3BAD0', '#C5D4E5', '#D9D9D9', '#FFFFF0', '#6B8FAD', '#E8E8DC'],
  shapeColors: {
    rectangle: '#FFFFF0',
    roundedRectangle: '#FFFFF0',
    diamond: '#8BA5BF',
    circle: '#A3BAD0',
    parallelogram: '#94a3b8',
    hexagon: '#8BA5BF',
    document: '#C5D4E5',
    cloud: '#A3BAD0',
    stickyNote: '#f0ece0',
    textbox: 'transparent',
    blockArrow: '#8BA5BF',
    chevronArrow: '#A3BAD0',
    doubleArrow: '#C5D4E5',
    circularArrow: '#94a3b8',
    ellipse: '#A3BAD0',
    group: '#FFFFF0',
  },
  defaultPaletteId: 'cyber',
};
