import type { DiagramStyle } from '../types';

export const gradientCards: DiagramStyle = {
  id: 'gradientCards',
  displayName: 'Gradient Cards',
  canvas: {
    background: '#f1f5f9',
    gridColor: '#e2e8f0',
    gridStyle: 'dots',
  },
  nodeDefaults: {
    fill: '#ffffff',
    stroke: 'transparent',
    strokeWidth: 0,
    borderRadius: 12,
    shadow: '0 1px 3px rgba(0, 0, 0, 0.08), 0 4px 12px rgba(0, 0, 0, 0.04)',
    fontFamily: "'Inter', system-ui, -apple-system, sans-serif",
    fontSize: 14,
    fontColor: '#334155',
    fontWeight: 500,
  },
  iconDefaults: {
    color: '#334155',
  },
  edgeDefaults: {
    stroke: '#cbd5e1',
    strokeWidth: 1,
    type: 'smoothstep',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: [
    '#6366f1',
    '#0ea5e9',
    '#14b8a6',
    '#f43f5e',
    '#a855f7',
    '#f97316',
    '#10b981',
  ],
  shapeColors: {
    rectangle: '#ffffff',
    roundedRectangle: '#ffffff',
    diamond: '#f97316',
    circle: '#14b8a6',
    parallelogram: '#a855f7',
    hexagon: '#f43f5e',
    document: '#0ea5e9',
    cloud: '#6366f1',
    stickyNote: '#fef3c7',
    textbox: 'transparent',
    blockArrow: '#f97316',
    chevronArrow: '#0ea5e9',
    doubleArrow: '#a855f7',
    circularArrow: '#14b8a6',
    ellipse: '#14b8a6',
    group: '#f8fafc',
  },
};
