import type { DiagramStyle } from '../types';

export const militaryC2: DiagramStyle = {
  id: 'militaryC2',
  displayName: 'Military C2',
  dark: true,
  canvas: {
    background: '#2b3023',
    gridColor: '#3d4435',
    gridStyle: 'lines',
  },
  nodeDefaults: {
    fill: '#3d4435',
    stroke: '#8b9a6b',
    strokeWidth: 2,
    borderRadius: 2,
    shadow: '0 1px 3px rgba(0, 0, 0, 0.4)',
    fontFamily: "'Share Tech Mono', 'Consolas', 'Courier New', monospace",
    fontSize: 12,
    fontColor: '#c8d4a8',
    fontWeight: 700,
  },
  edgeDefaults: {
    stroke: '#8b9a6b',
    strokeWidth: 2,
    type: 'step',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: ['#4a90d9', '#d94a4a', '#5cb85c', '#f0ad4e', '#c8d4a8'],
  defaultPaletteId: 'military',
  shapeColors: {
    rectangle: '#3d4435',
    roundedRectangle: '#3d4435',
    diamond: '#b8860b',
    circle: '#556b2f',
    parallelogram: '#6b8e23',
    hexagon: '#8b4513',
    document: '#2e8b57',
    cloud: '#708090',
    stickyNote: '#f0e68c',
    textbox: 'transparent',
    blockArrow: '#556b2f',
    chevronArrow: '#6b8e23',
    doubleArrow: '#4b5320',
    circularArrow: '#8b4513',
  },
};
