import type { DiagramStyle } from '../types';

export const openAI: DiagramStyle = {
  id: 'openAI',
  displayName: 'OpenAI',
  dark: false,
  canvas: {
    background: '#ffffff',
    gridColor: '#e5e5e5',
    gridStyle: 'dots',
  },
  nodeDefaults: {
    fill: '#212121',
    stroke: '#3a3a3a',
    strokeWidth: 1,
    borderRadius: 8,
    shadow: '0 1px 4px rgba(0, 0, 0, 0.12)',
    fontFamily: "'Inter', 'Söhne', 'Helvetica Neue', sans-serif",
    fontSize: 14,
    fontColor: '#ececec',
    fontWeight: 400,
  },
  iconDefaults: {
    color: '#ececec',
  },
  edgeDefaults: {
    stroke: '#10a37f',
    strokeWidth: 1.5,
    type: 'smoothstep',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: ['#10a37f', '#1a7f64', '#5cead4', '#212121', '#6e6e6e', '#0d8c6d', '#9e9e9e'],
  shapeColors: {
    rectangle: '#212121',
    roundedRectangle: '#212121',
    diamond: '#1a3a30',
    circle: '#10a37f',
    parallelogram: '#2a2a2a',
    hexagon: '#1a7f64',
    document: '#2a2a2a',
    cloud: '#2a2a2a',
    stickyNote: '#3a3a2a',
    textbox: 'transparent',
    blockArrow: '#2a2a2a',
    chevronArrow: '#10a37f',
    doubleArrow: '#2a2a2a',
    circularArrow: '#2a2a2a',
    ellipse: '#10a37f',
    group: '#2a2a2a',
  },
};
