import type { DiagramStyle } from '../types';

export const pastelSoft: DiagramStyle = {
  id: 'pastelSoft',
  displayName: 'Pastel Soft',
  canvas: {
    background: '#fefcfb',
    gridColor: '#f0e6e0',
    gridStyle: 'dots',
  },
  nodeDefaults: {
    fill: '#e8dff5',
    stroke: '#c9b8e8',
    strokeWidth: 1.5,
    borderRadius: 16,
    shadow: '0 2px 8px rgba(180, 160, 210, 0.2)',
    fontFamily: "'Nunito', 'Quicksand', 'Segoe UI', sans-serif",
    fontSize: 14,
    fontColor: '#2d2347',
    fontWeight: 600,
  },
  edgeDefaults: {
    stroke: '#c9b8e8',
    strokeWidth: 1.5,
    type: 'smoothstep',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: ['#c3aed6', '#a8d8b9', '#f6c6a8', '#f7a8b8', '#a8d4f0'],
  shapeColors: {
    rectangle: '#e8dff5',
    roundedRectangle: '#e8dff5',
    diamond: '#fbbf24',
    circle: '#6ee7b7',
    parallelogram: '#c4b5fd',
    hexagon: '#fda4af',
    document: '#93c5fd',
    cloud: '#a5b4fc',
    stickyNote: '#fef3c7',
    textbox: 'transparent',
    blockArrow: '#c3aed6',
    chevronArrow: '#a8d8b9',
    doubleArrow: '#f6c6a8',
    circularArrow: '#f7a8b8',
  },
};
