import type { DiagramStyle } from '../types';

export const whiteboardSketch: DiagramStyle = {
  id: 'whiteboardSketch',
  displayName: 'Whiteboard Sketch',
  canvas: {
    background: '#faf8f5',
    gridColor: '#e8e4de',
    gridStyle: 'dots',
  },
  nodeDefaults: {
    fill: '#fffdf7',
    stroke: '#5c5346',
    strokeWidth: 2,
    borderRadius: 6,
    shadow: 'none',
    fontFamily: "'Caveat', 'Patrick Hand', 'Comic Sans MS', cursive",
    fontSize: 18,
    fontColor: '#3d3529',
    fontWeight: 700,
  },
  edgeDefaults: {
    stroke: '#5c5346',
    strokeWidth: 2,
    type: 'default',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: ['#e74c3c', '#2980b9', '#27ae60', '#f39c12', '#8e44ad'],
  shapeColors: {
    rectangle: '#faf8f5',
    roundedRectangle: '#faf8f5',
    diamond: '#f59e0b',
    circle: '#34d399',
    parallelogram: '#a78bfa',
    hexagon: '#fb7185',
    document: '#60a5fa',
    cloud: '#818cf8',
    stickyNote: '#fef3c7',
    textbox: 'transparent',
    blockArrow: '#8b6f47',
    chevronArrow: '#a0845c',
    doubleArrow: '#7a6240',
    circularArrow: '#6b5335',
  },
};
