import type { DiagramStyle } from '../types';

export const zincModern: DiagramStyle = {
  id: 'zincModern',
  displayName: 'Zinc Modern',
  canvas: {
    background: '#f4f4f5',
    gridColor: '#e4e4e7',
    gridStyle: 'lines',
  },
  nodeDefaults: {
    fill: '#ffffff',
    stroke: '#a1a1aa',
    strokeWidth: 1,
    borderRadius: 8,
    shadow: 'none',
    fontFamily: "'Inter', 'SF Pro Display', system-ui, sans-serif",
    fontSize: 13,
    fontColor: '#27272a',
    fontWeight: 500,
  },
  edgeDefaults: {
    stroke: '#a1a1aa',
    strokeWidth: 1,
    type: 'smoothstep',
    animated: false,
    arrowType: 'arrowclosed',
  },
  accentColors: ['#3f3f46', '#71717a', '#0ea5e9', '#8b5cf6', '#f59e0b'],
  shapeColors: {
    rectangle: '#ffffff',
    roundedRectangle: '#ffffff',
    diamond: '#f59e0b',
    circle: '#10b981',
    parallelogram: '#8b5cf6',
    hexagon: '#ef4444',
    document: '#3b82f6',
    cloud: '#6366f1',
    stickyNote: '#fef9c3',
    textbox: 'transparent',
    blockArrow: '#3f3f46',
    chevronArrow: '#71717a',
    doubleArrow: '#a1a1aa',
    circularArrow: '#52525b',
  },
};
